version: '3.8'

services:
  auth:
    build: 
      context: ./services/auth
    ports:
      - "5001:5001"
    depends_on: 
      - db
    env_file:
      - ./services/auth/.env.prod
    container_name: auth-service
  db:
    image: mongo:latest
    restart: always
    ports:
      - "27027:27017"
    env_file:
      - ./.env.prod
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  default:
    driver: bridge
    