version: '3.8'

services:

  gateway:
    build:
      context: ./services/gateway-service
    ports:
      - "8080:8080"
    env_file:
      - ./services/gateway-service/.env.prod
    depends_on:
      - auth_service



  auth_service:
    container_name: auth-service
    build:
      context: ./services/auth
    depends_on:
      - db
    env_file:
      - ./services/auth/.env.prod

  db:
    image: mongo:latest
    restart: always
    ports:
      - "27027:27017"
    env_file:
      - ./services/auth/.env.prod
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  default:
    driver: bridge
    