version: '3.8'

services:

  gateway:
    build:
      context: ./services/gateway-service
    ports:
      - "8080:8080"
    env_file:
      - ./services/gateway-service/.env.prod
    depends_on:
      - auth_service
      - products_service
      - blogs_service
      - reviews_service

  auth_service:
    container_name: auth-service
    build:
      context: ./services/auth
    depends_on:
      - db
    env_file:
      - ./services/auth/.env.prod

  products_service:
    container_name: products-service
    build:
      context: ./services/products-service
    depends_on:
      - db
    env_file:
      - ./services/products-service/.env.prod

  blogs_service:
    container_name: blogs-service
    build:
      context: ./services/blogs-service
    depends_on:
      - db
    env_file:
      - ./services/blogs-service/.env.prod    

  reviews_service:
    container_name: reviews-service
    build:
      context: ./services/reviews-service
    depends_on:
      - db
    env_file:
      - ./services/reviews-service/.env.prod    

  db:
    image: mongo:latest
    restart: always
    ports:
      - "27027:27017"
    env_file:
      - ./services/auth/.env.prod
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  default:
    driver: bridge
    