service:
  name: "products-service"
  port: 8080
  log_level: "debug" 

mongodb:
  uri: "mongodb://localhost:27017"
  database: "laptopStore"
  collections:
    products: "products"
    reviews: "reviews"
    categories: "categories"