version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_cart
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  cart-service:
    build: .
    container_name: cart_service
    restart: always
    environment:
      MONGO_URI: "mongodb://root:example@mongodb:27017"
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongo_data:
